language: python
cache: pip
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
install:
  - pipenv install --dev
scripts:
  - pytest
  - pytest --flake8
  - pytest --pylint
addons:
  apt:
    update: true
    packages:
      - clang
