name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    env:
      VIRTUAL_ENV: .local/share/virtualenvs/compiler

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache virtualenv
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: |
          ~/.cache/pip
          ~/.local/share/virtualenvs
        # Look to see if there is a cache hit for the corresponding requirements file
        key: v1-${{ runner.os }}-virtualenv-${{ matrix.python-version }}-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          v1-${{ runner.os }}-virtualenv-${{ matrix.python-version }}-

    - name: Install dependencies
      run: |
        python -m venv $VIRTUAL_ENV
        source $VIRTUAL_ENV/bin/activate
        python -m pip install pipenv
        python -m pipenv install --dev

    - name: Test with pytest
      run: |
        source $VIRTUAL_ENV/activate
        python -m pytest --pylint --flake8
